export const LOCAL_STORAGE_KEY_USER = "LOCAL_STORAGE_KEY_USER";
export const LOCAL_STORAGE_KEY_TOKEN = "LOCAL_STORAGE_KEY_TOKEN";
export const LOCAL_STORAGE_KEY_REFRESH_TOKEN =
  "LOCAL_STORAGE_KEY_REFRESH_TOKEN";
